name: 17th-june
on:
  push:

jobs:
  june:
    runs-on: ubuntu-latest 
    steps:
  
      - uses: actions/checkout@v2

      - name: Who started this workflow
        run: |
          echo "This workflow is started by {{ github.event.repository.name }}" 

      - name: Who started this workflow
        if: ${{ github.event.repository.name }} == 'new1' 
        run: |
          if: ${{ github.event.repository.name }} == 'new1' 
          echo "This workflow is started by {{ github.event.repository.name }}" 
          
      - name: Who started this workflow
        if: ${{ github.event.repository.name }} == 'new1' 
        run: |
          if: ${{ github.event.repository.name }} == 'Lead-Api' 
          echo "This workflow is started by {{ github.event.repository.name }}" 
          
      - name: Who started this workflow
        if: ${{ github.event.repository.name }} == 'Lead-Api' 
        run: |
          if: ${{ github.event.repository.name }} == 'new1' 
          echo "This workflow is started by {{ github.event.repository.name }}" 
