
name: tagging based on commit in master branch
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        
      - name: display commit message
        run: echo "${{ github.event.head_commit.message }}"
        
      - name: verify the valid commit message received or not for tagging 
        run: |
          if [[ ${{ github.event.head_commit.message }} == v*.*.* ]] || [[ ${{ github.event.head_commit.message }} == V*.*.* ]]; then exit 0; else exit 1; fi
        
      - name: store tag name
        run: echo "TAG_NAME=$(echo "${{ github.event.head_commit.message }}" | cut -d':' -f1)" >> $GITHUB_ENV
          
      - name: tag the master branch
        run: git tag "${{ env.TAG_NAME }}"     
        
      - name: push the tag to remote
        run: git push origin "${{ env.TAG_NAME }}"     
        
   #hello how are u     
        
