name: checkvaraiblechnag
on:
  workflow_dispatch:

jobs:
  checkvaraiblechnag:
    runs-on: ubuntu-latest 
    steps:
  
      - uses: actions/checkout@v2

      - name: Set GitHub_Env value
        run: |
          echo "HOSTNAME=$(echo "hellosir")" >> $GITHUB_ENV
          
      - name: Display GitHub_Env values
        run: |
          echo "The hostname is ${{ env.HOSTNAME }}"

      - name: Set GitHub_Env value
        run: |
          echo "HOSTNAME=$(echo "hellomadam")" >> $GITHUB_ENV
          
      - name: Display GitHub_Env values
        run: |
          echo "The hostname is ${{ env.HOSTNAME }}"
