name: check
on: 
  push:    

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set the ${{ github.repository }}
        run: echo "hello world"
 
      
    
