name: tagging based input
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

jobs:
  build:
    if: |
      github.ref_name == 'master' && github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: tag the master branch
        run: echo "$ENVIRONMENT"
      
        
      - name: verify the valid commit message received or not for tagging 
        run: |
          if [[ $ENVIRONMENT == v*.*.* ]] || [[ $ENVIRONMENT == V*.*.* ]]; then exit 0; else exit 1; fi
        
      - name: tag the master branch
        run: git tag "$ENVIRONMENT"     
        
      - name: push the tag to remote
        run: git push origin "$ENVIRONMENT"     
        
        
   
        
        
