name: prod-ci-test
on: 
  workflow_dispatch:
    inputs:
      tagname:
        description: 'enter the tag name'     
        required: true
        default: 'warning' 
  push: 
    tag:
      - v*.*.*

jobs:
  prod-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: display eniromntal varaiable
        run: | 
          echo "${{ github.event.inputs.tagname }}"   
          echo "${{ github.ref_name }}"
          echo "${{ github.ref_type }}"
          echo "${{ github.event }}"
          echo "${{ github.event_name }}"    
