name: tagging based input
on: 
  workflow_dispatch:
    inputs:
      tagname:
        description: 'enter the tag name (v*.*.*)'     
        required: true
        default: 'warning' 
  push:    
    branches: 
      - 'master'

jobs:
  build:
    if: |
      github.ref_name == 'master' && github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
#       - name: tag the master branch
#         run: echo "${{ github.event.inputs.tagname }}"
        
      - name: display eniromntal varaiable
        run: | 
          echo "${{ github.event.inputs.tagname }}"   
          echo ${{ github.ref_name }}
          echo ${{ github.ref_type }}
          echo ${{ github.event }}
          echo ${{ github.event_name }}
      
        
#       - name: verify the valid commit message received or not for tagging 
#         run: |
#           if [[ ${{ github.event.inputs.tagname }} == v*.*.* ]] || [[ ${{ github.event.inputs.tagname }} == V*.*.* ]]; then exit 0; else exit 1; fi
        
#       - name: tag the master branch
#         run: git tag "${{ github.event.inputs.tagname }}"     
        
#       - name: push the tag to remote
#         run: git push origin "${{ github.event.inputs.tagname }}"     
