name: tagging based on commit in master branch
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

        
      - name: docker images
        run: |
          echo "TAG_NAME=v100.100.100" >> $GITHUB_ENV
          
      - name: docker images
        run: echo "${{ env.TAG_NAME }}"
            
      - name: check tag status
        run: |
          if [[ ${{ env.TAG_NAME }} == v*.*.* ]] || [[ ${{ env.TAG_NAME }} == V*.*.* ]]; then exit 0; else exit 1; fi
        
      - name: docker images
        run: docker images 
        
        

















